### ISSUE TITLE
INTRINSICOS

### ISSUE THREAD

**Issue by edwardes2201** [YWL0720/FAST-LIO-COLOR-MAPPING#1]
HELLO FRIEND, I WANT TO TEST YOUR CODE, I HAVE A LIVOX MID 40, MID 360 AND REALSENSE D435I, BUT I CAN'T FIND THE INTRINSIC PARAMETERS OF THE CAMERA.
WHERE YOU OBTAINED THE INTRISE PARAMETERS OF YOUR CAMERA. GREETINGS

......color_mapping:
    K_camera: [897.2655639648438, 0.0, 667.4661254882813,
               0.0, 897.6438598632813, 383.1944580078125,
               0.0, 0.0, 1.0]
    D_camera: [0.16910859942436218, -0.5095232725143433, -0.0025386682245880365, 0.0001707322953734547, 0.4606553614139557]

**Comment by YWL0720** [comment]
You can get the factory intrinsic parameters of the camera by using **_rostopic echo /camera/color/camera_info_** while running the camera driver, for example, **_roslaunch realsense2_camera rs_camera.launch_**. Of course, you can also recalibrate to get more accurate intrinsic parameters using some camera calibration tools, such as [camera_calibration](http://wiki.ros.org/camera_calibration)
