### ISSUE TITLE
save pcd issue

### ISSUE THREAD

**Issue by giangdao1402** [YWL0720/FAST-LIO-COLOR-MAPPING#2]
i encounter this problem
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Error during open!

**Comment by YWL0720** [comment]
You can use this to save the pcd
```cpp
#include <ros/ros.h>
#include <sensor_msgs/PointCloud2.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/filters/voxel_grid.h>
#include <csignal>
using namespace std;

typedef pcl::PointXYZRGB PointType;

pcl::PointCloud<PointType>::Ptr pc(new pcl::PointCloud<PointType>);
pcl::VoxelGrid<PointType>::Ptr voxel(new pcl::VoxelGrid<PointType>);

void SigHandle(int sig)
{
    ROS_INFO("Start write pcd");
    voxel->setInputCloud(pc);
    voxel->filter(*pc);
    pcl::io::savePCDFile("/home/ywl/map.pcd", *pc);
    ROS_INFO("Done");
    ros::shutdown();
}

void PointCloudCallback(const sensor_msgs::PointCloud2ConstPtr& msg_pc)
{
    pcl::PointCloud<PointType>::Ptr temp(new pcl::PointCloud<PointType>);
    pcl::fromROSMsg(*msg_pc, *temp);
    *pc += *temp;
}

int main(int argc, char** argv)
{
    ros::init(argc, argv, "catcher");
    ros::NodeHandle nh;
    signal(SIGINT, SigHandle);
    voxel->setLeafSize(0.01, 0.01, 0.01);
    ros::Subscriber pc_sub = nh.subscribe<sensor_msgs::PointCloud2>("/color_pc", 100, PointCloudCallback);

    ros::spin();

    return 0;
}

```
Or maybe later, I will submit a new piece of code to add an interface for saving the map

**Comment by giangdao1402** [comment]
the map given by saving pcd file is bad, but rviz is ok. How can that happen ?

**Comment by YWL0720** [comment]
If it's convenient, you could also upload your dataset, and I will test it again.

**Comment by giangdao1402** [comment]
Hey i have uploaded dataset follow this link: https://nghiensetups-my.sharepoint.com/:f:/g/personal/truonggiangds14_nghiensetups_net/En7YcmtjUGRJgJQ7Yrf4lM8BBsyM8bKzn8vpoqmO9qhqGQ?e=f1wMBh
It include python file to publish image from folder image(right).
I have tried config and launch files so you do not need to config.
Just need to run bag, launch file and file python
Thank you.
